- name: Installing NVIDIA gfx drivers
  block:
    - name: nvidia - install driver 510
      apt:
        #update_cache: yes
        pkg:
          - nvidia-driver-510
        state: present

    - name: nvidia - remove xorg nouveau driver
      apt:
        pkg:
          - xserver-xorg-video-nouveau
        state: absent

    - name: nvidia - autoremove orphanned packages
      apt:
        autoremove: yes

    - name: nvidia - reinstall usual xorg gxf-drivers
      apt:
        pkg:
          - libxatracker2
          - libxvmc1
          - xserver-xorg-video-amdgpu
          - xserver-xorg-video-ati
          - xserver-xorg-video-fbdev
          - xserver-xorg-video-intel
          - xserver-xorg-video-qxl
          - xserver-xorg-video-radeon
          - xserver-xorg-video-vesa
  tags:
    - software-all
    - driver-nvidia
