- name: upgrade system
  block:
    - name: killing any running update process
      shell: pkill apt-get; pkill dpkg; sleep 2

    - name: apt - upgrading
      apt:
        update_cache: yes
        upgrade: yes
      register: apt_upgrade
      retries: 5
      until: apt_upgrade is success
  notify: reboot system
  tags:
    - software-all
    - software-default
    - upgrade

- name: apt -autoremove orphanned packages
  apt:
    autoremove: yes
  tags:
    - software-all
    - software-default
    - upgrade

- name: run queued handlers
  meta: flush_handlers
  tags:
    - software-all
    - software-default
    - upgrade

- name: apt - software-default
  block:
    - name: running software installation
      apt:
        pkg:
          - ansible
          - ansible-lint
          - bing
          - build-essential
          - ceph-common
          - ceph-fuse
          - code
          - containerd.io
          - cowsay
          - cpp
          - curl
          - docker-ce
          - docker-compose
          - firefox
          - gcc
          - git
          - git-lfs
          - google-chrome-stable
          - htop
          - ipython3
          - kubeadm
          - kubectl
          - libxml2-utils
          - nodejs
          - openssh-client
          - openssh-server
          - postgresql
          - postgresql-client
          - postgresql-contrib
          - python3
          - python3-pip
          - python3-venv
          - qemu-kvm
          - qgis
          - ssh-import-id
          - sshpass
          - ubuntu-oem-keyring
          - unzip
          - vim
          - xfsprogs
        state: present
        update_cache: yes
  tags:
    - software-all
    - software-default
    - software-apt

- name: system - deploy pip config for nexus
  template:
    src: pip.j2
    dest: /etc/pip.conf
    owner: root
    group: root
    mode: 0644
    backup: no
  tags:
    - software-all
    - software-default

- name: apt - install golang 1.18 from ppa
  block:
    - apt:
        pkg: golang-1.18
        state: present
        update_cache: no
    - file:
        src: /usr/lib/go-1.18/bin/go
        dest: /usr/bin/go
        state: link
  tags:
    - software-all
    - software-default
    - software-apt
    - golang

- name: sideload - install nexus-sync
  block:
    - copy:
        src: nexus-sync
        dest: /usr/local/sbin
        owner: root
        group: root
        mode: 0755
        backup: no
    - copy:
        src: ns-import.conf
        dest: /etc
        owner: root
        group: root
        mode: 0644
        backup: no
  tags:
    - software-all
    - software-default

- name: sideload - install yq
  get_url:
    url: "{{nexus_proxy_proto}}://{{nexus_proxy}}:{{nexus_proxy_port}}/repository/raw-github/mikefarah/yq/releases/{{ version_yq }}/download/yq_linux_amd64"
    dest: /usr/local/sbin/yq
    owner: root
    group: root
    mode: 0755
  tags:
    - software-all
    - yq

- name: sideload - install k9s
  unarchive:
    src: "{{nexus_proxy_proto}}://{{nexus_proxy}}:{{nexus_proxy_port}}/repository/raw-github/derailed/k9s/releases/{{ version_k9s }}/download/k9s_Linux_x86_64.tar.gz"
    dest: /usr/local/sbin
    extra_opts: [--strip-components=0, k9s]
    remote_src: yes
    owner: root
    group: root
    mode: 0755
  tags:
    - software-all
    - k9s

- name: sideload - install helm
  unarchive:
    src: "{{nexus_proxy_proto}}://{{nexus_proxy}}:{{nexus_proxy_port}}/repository/raw-helm/helm-{{ version_helm }}-linux-amd64.tar.gz"
    dest: /usr/local/sbin
    extra_opts: [--strip-components=1, linux-amd64/helm]
    remote_src: yes
    owner: root
    group: root
    mode: 0755
  tags:
    - software-all
    - helm

- name: sideload - install Terraform
  unarchive:
    src: "{{nexus_proxy_proto}}://{{nexus_proxy}}:{{nexus_proxy_port}}/repository/raw-hashicorp/terraform/{{ version_terraform }}/terraform_{{ version_terraform }}_linux_amd64.zip"
    dest: /usr/local/sbin
    remote_src: yes
    owner: root
    group: root
    mode: 0755
  tags:
    - software-all
    - terraform

- name: sideload - create global Terraform Proxmox plugin folder
  file:
    path: /usr/local/share/terraform/plugins/registry.terraform.io/telemate/proxmox/{{ version_terraform_provider_proxmox }}/download/linux_amd64
    state: directory
    owner: root
    group: root
    mode: 0755
    recurse: yes
  tags:
    - software-all
    - terraform

- name: sideload - install Terraform Proxmox plugin
  unarchive:
    src: "{{nexus_proxy_proto}}://{{nexus_proxy}}:{{nexus_proxy_port}}/repository/raw-github/Telmate/terraform-provider-proxmox/releases/latest/download/terraform-provider-proxmox_{{version_terraform_provider_proxmox}}_linux_amd64.zip"
    dest: /usr/local/share/terraform/plugins/registry.terraform.io/telemate/proxmox/{{ version_terraform_provider_proxmox }}/download/linux_amd64/
    remote_src: yes
    owner: root
    group: root
    mode: 0755
  tags:
    - software-all
    - terraform
